### PR TITLE
chore: run CI for with no default features

### PR DESCRIPTION
**Pull request by vmx**
I runs Clippy with no default features, which is similar to just building
the project.

### CODE REVIEW

**Comment by dvc94ch** [comment]
That means clippy doesn't run on all the code...

**Comment by dvc94ch** [comment]
I see

**Comment by vmx** [comment]
Yes, building tests without the default features leads to lots of errors. I don't know if we would want to support that.

**Comment by dvc94ch** [comment]
No tests should run with all features

**Pull request merged**
